### ISSUE TITLE
Unable to insert messages to Testcase after the Run has been ended

### ISSUE THREAD

**Issue by stkomitov** [Axway/ats-httpdblogger#3]
To achieve "real time" test state representation in TestExplorer, I'm logging the run/suite/scenario/testcase start/end events separate from the logging message events (which are a lot) and I found that when the Run is already ended the logging messages per some of its tests are being ignored, and doesn't present in TestExplorer.

**Comment by dslaveykov** [comment]
Hello, the issue has been resolved.
You can try the new code in the snapshot after 5-10 minutes.

**Comment by stkomitov** [comment]
Yep, it is now working fine. Thank you for the fast reaction.
