### ISSUE TITLE
[Enhancement] Ability to upload attachments to test cases using the REST API

### ISSUE THREAD

**Issue by achuchev** [Axway/ats-httpdblogger#4]
Test Explorer provides ability to show attachments (like log files). In our case we want to upload screenshot images of the browser in case there is failure in the UI. Currently, there is no way to upload attachments using the REST API.

So, I would like to request it. Let me know if you have any questions.

**Comment by dslaveykov** [comment]
Enhancement implemented and will be available in 4.0.2 release
